[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "0.1.0"
name = "source-brightdata-serp"
description = "Source implementation for Bright Data SERP."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "ELv2"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/brightdata-serp"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_brightdata_serp"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
airbyte-cdk = "^2"
requests = "^2.28.0"
pendulum = "^2.1.2"

[tool.poetry.scripts]
source-brightdata-serp = "source_brightdata_serp.run:run"

[tool.poetry.group.dev.dependencies]
requests-mock = "^1.9.3"
pytest-mock = "^3.12.0"
pytest = "^8.0.0"

[tool.poe]
include = [
    "${POE_GIT_DIR}/poe-tasks/poetry-connector-tasks.toml",
]